# Generated by Django 5.0.4 on 2024-05-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lecutres/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='lecture-thumbnails/'),
        ),
    ]
