# Generated by Django 5.0 on 2025-04-16 06:22

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default=courses.models.default_course_image, null=True, upload_to='courses/'),
        ),
    ]
